# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard 'go', server: 'cat.go', args: ['Gemfile'] do
  watch(%r{cat\.go$})
end

guard 'go', server: 'grep.go', args: ['gem', 'Gemfile'] do
  watch(%r{grep\.go$})
end
